apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-plugin
  namespace: openshift-gitops
  labels:
    app: gitops-plugin
    app.kubernetes.io/component: gitops-plugin
    app.kubernetes.io/instance: gitops-plugin
    app.kubernetes.io/part-of: gitops-plugin
    app.openshift.io/runtime-namespace: openshift-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-plugin
  template:
    metadata:
      labels:
        app: gitops-plugin
    spec:
      containers:
        - name: gitops-plugin
          image: quay.io/redhat-developer/gitops-console-plugin
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: console-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
            - name: nginx-conf
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420
        - name: nginx-conf
          configMap:
            name: nginx-conf
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: openshift-gitops
  labels:
    app: gitops-plugin
    app.kubernetes.io/part-of: gitops-plugin
data:
  nginx.conf: |
    error_log /dev/stdout info;
    events {}
    http {
      access_log         /dev/stdout;
      include            /etc/nginx/mime.types;
      default_type       application/octet-stream;
      keepalive_timeout  65;
      server {
        listen              9001 ssl;
        ssl_certificate     /var/serving-cert/tls.crt;
        ssl_certificate_key /var/serving-cert/tls.key;
        root                /usr/share/nginx/html;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
  name: gitops-plugin
  namespace: openshift-gitops
  labels:
    app: gitops-plugin
    app.kubernetes.io/component: gitops-plugin
    app.kubernetes.io/instance: gitops-plugin
    app.kubernetes.io/part-of: gitops-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: gitops-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: gitops-plugin
spec:
  displayName: "GitOps Plugin"
  service:
    name: gitops-plugin
    namespace: openshift-gitops
    port: 9001
    basePath: "/"